#!/usr/bin/python

import socket;
import argparse
import sys

# define and gather command line options
parser = argparse.ArgumentParser(description='Check open ports for Monitoring.')

parser.add_argument(
    "-H",
    "--host",
    dest="host",
    help="Which host to connect to."
)

parser.add_argument(
    "-p",
    "--port",
    dest="port",
    type=int,
    help="Which port to connect to."
)

# Parse Arguments
options = parser.parse_args()

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
result = sock.connect_ex((options.host, options.port))
if result != 0:
    sys.stdout.write('CRIT - Port %s Not Open\n' % (options.port))
    sys.exit(2)
else:
    sys.stdout.write('OK - Port %s Open\n' % (options.port))
